###############################
#    BedwarsXP  经验起床插件    #
#          By.Ldcr            #
###############################

#设置资源可兑换为的XP数
XP:
    #铜可兑换为的XP
    bronze: 1
    #铁可兑换为的XP
    iron: 5
    #金可兑换为的XP
    gold: 10
    #如有其他自行添加的资源也可以在此处按格式添加
    #custom: 233
#请务必保证起床插件中配置的资源在此处都有对应经验值

#获得XP的提示
#使用%xp%代替获得的XP
#插件会尝试使用ActionBar来发送,如发送失败(版本不匹配等原因)会使用聊天发送
#更改为空('')来禁用发送信息
Message: '&a你获得了 &6&l%xp% &a点经验'

#是否在商店新增将经验重新兑换回铜铁金的菜单
Add_Res_Shop: true

#玩家死亡丢失经验
#设置为数值来扣除固定经验,或者末尾加上百分号来按百分比扣经验
Death: 0

#完全经验起床模式
#设置为false : 玩家捡取资源获得经验,在商店将经验重新兑换回铜铁金购买东西
#设置为true  : 玩家捡取资源获得经验,并可以在商店直接使用经验购买东西
Full_XP_Bedwars: false

#配置文件版本
#请不要动这个
ConfigVersion: 1

